### ISSUE TITLE
Uncaught TypeError in script.js

### ISSUE THREAD

**Issue by ravin972** [ravin972/cuberto_clone#1]
# Issue: Uncaught TypeError in script.js

## Description

In the `script.js` file, an Uncaught TypeError is being encountered at line 30, where `ScrollTrigger.create` is used, but it is not recognized as a function. This error disrupts the expected behavior of the script.

### Error Details

- **File**: script.js
- **Line**: 30
- **Error Message**: Uncaught TypeError: ScrollTrigger.create is not a function

## Steps to Reproduce

1. Open the project in a web browser.
2. Inspect the browser console.
3. Navigate to the `script.js` file and locate line 30.
4. Observe the Uncaught TypeError message.

## Expected Behavior

The `ScrollTrigger.create` function should be recognized and execute without errors.

## Suggested Fix

1. Verify that the ScrollTrigger library is correctly loaded and accessible in your project.
2. Ensure that the library is loaded before using it in your `script.js`.
3. Double-check for any potential typos or naming issues in your code.
### 4. Want to fix this screenshot 
  ![Screenshot (1)](https://github.com/ravin972/cuberto_clone/assets/59820924/0e439a19-e153-46f9-8523-6972fc20e686)
### when i comment out this :
![Screenshot (2)](https://github.com/ravin972/cuberto_clone/assets/59820924/baa717f8-e00e-4edd-8f34-3f56bc18d2eb)
### the issue images is showing.

Please address this issue to enable the correct functioning of your script.

**Comment by keshav-gupta19** [comment]
I want to work on this issue.

**Comment by ravin972** [comment]
> I want to work on this issue.
![image](https://github.com/ravin972/cuberto_clone/assets/59820924/0b26a68d-e507-4669-b056-f723e9c84eb0)
